### ISSUE TITLE
Allow gif voting

### ISSUE THREAD

**Issue by RaceFPV** [slashrocket/reactif#1]
1. Create a table to store each gif and its vote count
2. By default give each gif 25 points to start
3. Using a mixture of percentage and total points, create a randomized gif selector based on # of votes out of 5 for each gif
   - a hard limit of 100 votes max should be in place
   - each gif should be tracked/indexed by its url
   - a query for new gifs should still take place, allowing for new gif entries into the pool
   - each gif should have a % out of 100% after all votes are divided by the max
4. Allow users to vote for a gif either by using a slash command or a link next to the gif in the slack chat

**Comment by 4xposed** [comment]
partially done by @4xposed in commits: 2e7a9772674eb3853777f55c0088cdf2388e1d3c and 56ec011963e4b23e901e301690851d2f836ff2ab
